# Generated by Django 3.0.7 on 2020-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
