# Generated by Django 3.0.7 on 2020-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='resouces/uploads')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('tags', models.ManyToManyField(to='resources.Tags')),
            ],
        ),
    ]
