# Generated by Django 3.0.7 on 2020-06-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='links',
            name='name',
            field=models.CharField(default='', max_length=220),
        ),
    ]
