# Generated by Django 3.0.7 on 2020-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/uploads'),
        ),
    ]
