# Generated by Django 3.0.7 on 2020-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200616_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
