# Generated by Django 3.0.7 on 2020-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='github_username',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='cf_username',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
